In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

df = pd.read_csv('DATASET_NB_ROOT/NB_6934069/Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
df=df.iloc[:, 1:]
df.head(3)

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0

In [7]:
df['Gender'] = np.where(df['Gender']=='Male', 1, 0)
df.head(3)

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0

In [9]:
x = df.iloc[:, :3].values
y = df.iloc[:, 3].values

from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x,y, test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtr = sc.fit_transform(xtr)
xts = sc.transform(xts)

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
dt2 = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=0)

dt1.fit(xtr, ytr)
dt1.feature_importances_
dt1.score(xtr, ytr)
dt1.score(xts, yts)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

array([ 0.       ,  0.5229604,  0.4770396])

0.91428571428571426

0.91666666666666663

In [16]:
dt2.fit(xtr, ytr)
dt2.feature_importances_
dt2.score(xtr, ytr)
dt2.score(xts, yts)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

array([ 0.        ,  0.58186785,  0.41813215])

0.91785714285714282

0.91666666666666663

In [18]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, max_depth=3, min_samples_split=2)
rf.fit(xtr, ytr)
rf.feature_importances_
rf.score(xtr, ytr)
rf.score(xts, yts)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

array([ 0.00188696,  0.52262051,  0.47549253])

0.92500000000000004

0.91666666666666663

In [19]:
ypr1 = dt1.predict(xts)
ypr2 = dt2.predict(xts)
ypr3 = rf.predict(xts)

from sklearn.metrics import  confusion_matrix
cm1 = confusion_matrix(yts, ypr1)
cm2 = confusion_matrix(yts, ypr2)
cm3 = confusion_matrix(yts, ypr3)

cm1
cm2
cm3

array([[72,  7],
       [ 3, 38]], dtype=int64)

array([[72,  7],
       [ 3, 38]], dtype=int64)

array([[73,  6],
       [ 4, 37]], dtype=int64)